### ISSUE TITLE
Readme incorrect ?

### ISSUE THREAD

**Issue by davecarlson** [redux-effects/redux-effects-localstorage#2]
`import localStorage from 'redux-effects-localStorage'
store.dispatch(localStorage.set('todos.0', 'Clean the kitchen'))`

should this not be :

`import localStorage from 'redux-effects-localstorage'
store.dispatch(localStorage.setItem('todos.0', 'Clean the kitchen'))`

**Comment by ashaffer** [comment]
Yep, thx. Fixed :).

**Comment by davecarlson** [comment]
There's a capital S in the import for the package name as well :)

Also, would it be possible to include an example of using the getItem version ?

**Comment by ashaffer** [comment]
What do you mean by in the import for the package name?

And ya sure i'll add an example for that.

**Comment by bsr203** [comment]
```
import localStorage from 'redux-effects-localStorage'

store.dispatch(localStorage.setItem('todos.0', 'Clean the kitchen'))
```

in this section of the readme, `import localStorage from 'redux-effects-localStorage'` -> `import localStorage from 'redux-effects-localstorage'`
